# This is the name of our workflow.
name: Continuous Integration

# This tells GitHub to run the workflow on every push to the 'main' branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# This defines the jobs to be run.
jobs:
  # This is the job for the backend.
  backend-ci:
    runs-on: ubuntu-latest
    # This line tells all 'run' steps in this job to execute inside the 'backend' folder.
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run placeholder test
        run: echo "Backend tests would run here."

  # This is the job for the frontend.
  frontend-ci:
    runs-on: ubuntu-latest
    # This line tells all 'run' steps in this job to execute inside the 'frontend' folder.
    defaults:
      run:
        working-directory: ./frontend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
