name: Build and Release Agent

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to upload assets

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build the Linux executable using a specialized action
      # This action handles all the complexities of creating a proper Linux binary.
      - name: Build with PyInstaller for Linux
        # THIS IS THE CORRECTED LINE - using the latest version of the action
        uses: cdrx/pyinstaller-action@v2
        with:
          # The path to our agent's main script
          path: ./agent
          # The name of the final executable file
          name: ai_agent
          # The script to build
          spec: main.py
          # Ensure it's a single file
          args: --onefile

      # Step 3: Upload the correctly built agent to the GitHub Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          # The path where the build action places the Linux executable
          asset_path: ./agent/dist/linux/ai_agent
          asset_name: ai_agent
          asset_content_type: application/octet-stream
