name: Build and Release Agent

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required to upload assets

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install dependencies, including PyInstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./agent/requirements.txt

      # Step 4: Build the Linux executable directly using PyInstaller
      - name: Build agent executable
        run: |
          python -m PyInstaller --onefile --name=ai_agent ./agent/main.py

      # Step 5: Upload the correctly built agent to the GitHub Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          # The path where PyInstaller places the final executable
          asset_path: ./dist/ai_agent
          asset_name: ai_agent
          asset_content_type: application/octet-stream
